apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
spec:
  selector:
    app: my-node-app
  ports:
    - protocol: TCP
      port: 80  # The port on which the service will be exposed
      targetPort: 4000  # The port on which your Node.js application is running
